<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<!--GENERATED BY:  Lectora Professional Publishing Suite v.2007 SP5(5100) (http://www.trivantis.com) -->


<head>
<title>title page</title>

<link rel="stylesheet" href="trivantis.css" type="text/css" />
<style text="text/css">
    body { background-color:#ffffff; }
    span.text40Font1 { font-size:37px; font-family:"Arial", sans serif; line-height:43px; color:#ffffff;}
</style>

<script language = "JavaScript" src="trivantis.js"></script>
<script language = "JavaScript" src="trivantis-button.js"></script>
<script language = "JavaScript" src="trivantis-image.js"></script>
<script language = "JavaScript" src="trivantis-inline.js"></script>
<script language = "JavaScript" src="trivantis-cookie.js"></script>
<script language = "JavaScript" src="trivantis-timedate.js"></script>
<script language = "JavaScript">

<!-- 
if( !is.min )
    document.write( 'Your browser does not support dynamic html. Please download a current version of either <a href="http://www.microsoft.com/ie/">Microsoft Internet Explorer</a> or <a href="http://www.netscape.com/">Netscape Navigator </a> and try visiting our site again.  Thank You.<br /><br />' )

var winW = screen.width
var winH = screen.height

function findWH() {
    winW = (is.ns)? window.innerWidth-16 : document.body.offsetWidth-20
    winH = (is.ns)? window.innerHeight   : document.body.offsetHeight
}

function ReFlow() {
    if (is.ns4 && winW && (winW!=window.innerWidth-16 || winH!=window.innerHeight))
      ObjLayerActionGoTo( 'index.cfm' )
}


onload = init
onunload = finish

function init() {
    findWH()
    if( is.min ){
        setTimeout( "preload( 'images/image_2020_51.jpg','images/image_20_52.jpg','images/platinum_exitoff.gif','images/platinum_exitclk.gif','images/platinum_exitrol.gif','images/platinum_nextoff.gif','images/platinum_nextclk.gif','images/platinum_nextrol.gif' )", 0 )
        button48.init()
        button47.init()
        text40.init()
        image42.init()
        image39.init()
        button48.activate()
        button47.activate()
        text40.activate()
        image42.activate()
        image39.activate()
        if( location.hash )
        {
            var newHash
            if( location.hash.charAt(0) == '#' )
                newHash = location.hash.slice( 1 )
            else
                newHash = location.hash
            location.hash = newHash
        }
        setTimeout( 'trivUpdateTOC( "index.cfm", "index.cfm", 1 )', 1000)
    }
}

var trivGoToPage = null
var trivCompleteCnt = 1;
var hasProcessedExitActions = false;
var trivWndFeedback = null;
var currFeedbackIdx = 0;
var trivPageExited = false;

function finish() {
}

function trivOnFocus() {
    if( trivWndFeedback )
    {
      try{if( !trivWndFeedback.closed )
      {
        trivWndFeedback.close()
        trivWndFeedback = null
      }}catch(e){}
      setTimeout( 'checkLeavePage()', 100)
    }
}

function checkLeavePage() {
    if( trivWndFeedback == null || trivWndFeedback.closed )
    {
        trivWndFeedback = null;
        currFeedbackIdx++;
        if( currFeedbackIdx > -1)
        {
            trivLeavePage();
          return;
        }
        else if( !checkQuestions( true ))
          return;
    }
    setTimeout( 'checkLeavePage()', 100)
}

function trivExitPage( newPage, bFeedback ) {
    if( newPage.indexOf( "ObjLayerAction" ) >= 0 || newPage.indexOf( ".action" ) >= 0 || newPage.indexOf( "history.back()" ) >= 0) trivGoToPage = newPage
    else trivGoToPage = 'ObjLayerActionGoTo("' + newPage + '")'
    if( !hasProcessedExitActions ) {
        findWH()
        hasProcessedExitActions = true
        setTimeout( 'checkLeavePage()', 100)
    }
}

function trivLeavePage() {
    trivCompleteCnt--
    if( trivCompleteCnt <= 0 ) {
        hasProcessedExitActions = false
        eval( trivGoToPage )
        trivGoToPage = null;
        trivPageExited = true;
    }
}

function trivPrevPage() {
}

function trivNextPage() {
    trivExitPage( 'page_20.html', true )
}

function trivUpdateTOC( currPage, parPage, bRecurse ) {
    var i
}

function trivUpdateEntry() {
}

function trivResetEntry() {
}

function action48(fn){
    trivExitPage('page_20.html',true);
    if(fn) eval(fn);
}

function button48onUp() {
  action48();
}

function action47(fn){
    {cleanupTitle('vx_plinth'); trivExitPage('ObjLayerActionExit()',false);} 
    if(fn) eval(fn);
}

function button47onUp() {
  action47();
}

if( is.min ){
button48 = new ObjButton('button48','Platinum Next',435,531,56,25,1,15,'div')
button48.setImages('images/platinum_nextoff.gif','images/platinum_nextclk.gif','images/platinum_nextrol.gif')
button48.onUp = button48onUp
button48.hasOnUp = true
button48.capture=4
button48.build()

button47 = new ObjButton('button47','Platinum Exit',391,529,28,28,1,16,'div')
button47.setImages('images/platinum_exitoff.gif','images/platinum_exitclk.gif','images/platinum_exitrol.gif')
button47.onUp = button47onUp
button47.hasOnUp = true
button47.capture=4
button47.build()

text40 = new ObjInline('text40',null,107,102,588,102,1,17,null,'div')
text40.build()

image42 = new ObjImage('image42','images/image_20_52.jpg','logo',698,11,60,86,1,18,'div')
image42.build()

image39 = new ObjImage('image39','images/image_2020_51.jpg','Image 2020',0,2,803,597,1,4,'div')
image39.build()



writeStyleSheets(
    button48.css+
    button47.css+
    text40.css+
    image42.css+
    image39.css
    )
}
// -->

</script>
</head>

<body onfocus="trivOnFocus()" onResize="ReFlow()">

<script language="JavaScript">
if( is.min ){
    document.write(button48.div)
    document.write(button47.div)
}
</script>

<div id="text40"><a name="text40anc"></a>
<p  style="margin-left:36px;text-indent:-36px;margin-bottom:0px;margin-top:0px;text-align:center;" >
<span class="text40Font1" >VX Plinth
</span ></p >
</div>

<script language="JavaScript">
if( is.min ){
    document.write(image42.div)
    document.write(image39.div)
}
</script>

</body>
</html>
