//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ac_products
    {
        public int id { get; set; }
        public string part_number { get; set; }
        public string type { get; set; }
        public string material { get; set; }
        public string voltage { get; set; }
        public string phase { get; set; }
        public string kw { get; set; }
        public string btu { get; set; }
        public string ul_nema { get; set; }
        public string description { get; set; }
    }
}
