//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accessory
    {
        public int id { get; set; }
        public string part_number { get; set; }
        public string product_type { get; set; }
        public string family { get; set; }
        public string group_1 { get; set; }
        public string group_2 { get; set; }
        public string description_1 { get; set; }
        public string description_2 { get; set; }
        public string description_3 { get; set; }
        public string color { get; set; }
        public string material { get; set; }
        public Nullable<short> PU { get; set; }
        public string link { get; set; }
    }
}
