//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adminPerm
    {
        public int ap_ID { get; set; }
        public Nullable<long> usr_ID { get; set; }
        public Nullable<byte> ap_user { get; set; }
        public Nullable<byte> ap_partner { get; set; }
        public Nullable<byte> ap_salesComms { get; set; }
        public Nullable<byte> ap_ru { get; set; }
        public Nullable<byte> ap_tools { get; set; }
        public Nullable<byte> ap_reports { get; set; }
        public Nullable<byte> ap_MDF { get; set; }
        public Nullable<byte> ap_QQ { get; set; }
        public Nullable<byte> ap_PR { get; set; }
        public Nullable<byte> ap_FX { get; set; }
        public Nullable<byte> ap_MDFA { get; set; }
        public Nullable<byte> ap_product { get; set; }
    }
}
