//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidRegistration
    {
        public int ID { get; set; }
        public string contact_name { get; set; }
        public string contact_email { get; set; }
        public string contact_phone { get; set; }
        public string customer_name { get; set; }
        public bool decision_maker { get; set; }
        public string company_name { get; set; }
        public string company_location { get; set; }
        public string project_location { get; set; }
        public string project_name { get; set; }
        public Nullable<System.DateTime> estimated_start_date { get; set; }
        public Nullable<decimal> project_value { get; set; }
        public string products { get; set; }
        public bool IT_distributor { get; set; }
        public string distributor_name { get; set; }
        public string project_type { get; set; }
        public string competition { get; set; }
        public string actions_required { get; set; }
        public string channel_manager_approval { get; set; }
        public string director_approval { get; set; }
        public string gm_approval { get; set; }
        public string files { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public Nullable<int> updated_by { get; set; }
        public int company_id { get; set; }
        public Nullable<byte> territory_manager_approved { get; set; }
        public Nullable<byte> director_approved { get; set; }
        public Nullable<byte> gm_approved { get; set; }
    }
}
