//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeCommissionPart
    {
        public int ID { get; set; }
        public int ChangeCommissionId { get; set; }
        public int part_number { get; set; }
        public int quantity { get; set; }
    
        public virtual ChangeCommission ChangeCommission { get; set; }
    }
}
