//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeCommission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChangeCommission()
        {
            this.ChangeCommissionParts = new HashSet<ChangeCommissionPart>();
        }
    
        public int ID { get; set; }
        public string number { get; set; }
        public byte full_request { get; set; }
        public int credit_sale { get; set; }
        public string to_representive { get; set; }
        public string from_representive { get; set; }
        public string account_number { get; set; }
        public string account_name { get; set; }
        public Nullable<int> sales_doc_number { get; set; }
        public string po_number { get; set; }
        public System.DateTime invoice_date { get; set; }
        public decimal amount { get; set; }
        public string reason { get; set; }
        public string request_representive { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> approved_on { get; set; }
        public Nullable<int> approved_by { get; set; }
        public Nullable<int> assigned_rep { get; set; }
        public Nullable<int> request_manager { get; set; }
        public Nullable<int> assigned_manager { get; set; }
        public Nullable<int> initialApproval { get; set; }
        public string FinalApproval { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChangeCommissionPart> ChangeCommissionParts { get; set; }
    }
}
