//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeCommissionHistory
    {
        public int ID { get; set; }
        public int ChangeCommissionId { get; set; }
        public int status { get; set; }
        public string notes { get; set; }
        public int assigned_to { get; set; }
        public System.DateTime created_on { get; set; }
        public int created_by { get; set; }
    }
}
