//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class email_tracker
    {
        public int ID { get; set; }
        public Nullable<int> usr_ID { get; set; }
        public string email_type { get; set; }
        public string msg_action { get; set; }
        public string url_tracked { get; set; }
        public Nullable<System.DateTime> date_sent { get; set; }
        public Nullable<System.DateTime> date_opened { get; set; }
    }
}
