//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fan_products
    {
        public int id { get; set; }
        public string part_number { get; set; }
        public string description { get; set; }
        public string cfm { get; set; }
        public string voltage { get; set; }
        public string color { get; set; }
        public string additional_description { get; set; }
    }
}
