//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Label
    {
        public int label_id { get; set; }
        public string label_name { get; set; }
        public string controller_name { get; set; }
        public string page_name { get; set; }
        public string translated_label { get; set; }
        public Nullable<int> language { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
