//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Large_enclosure_pricing
    {
        public int ID { get; set; }
        public string Doors { get; set; }
        public string Part_Number { get; set; }
        public string Description { get; set; }
        public string Price { get; set; }
        public string Part_Of_Selector { get; set; }
        public string Type { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public string Depth { get; set; }
    }
}
