//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Large_enclosure_myaccessories
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Code { get; set; }
        public string Config_name { get; set; }
        public string Part_Number { get; set; }
        public string Description { get; set; }
        public string Quantity_Per_Pack { get; set; }
        public string Number_of_Packs { get; set; }
        public string Unit_Cost { get; set; }
        public string Total_Cost { get; set; }
        public string Accessory_Number { get; set; }
        public string Baying_NotBaying { get; set; }
        public string Type { get; set; }
        public string Doors { get; set; }
        public string Height { get; set; }
    }
}
