//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Large_enclosure_ts8
    {
        public int ID { get; set; }
        public string TS8_partnumber { get; set; }
        public string Accessory_partnumber { get; set; }
        public string Height { get; set; }
        public string Width { get; set; }
        public string Depth { get; set; }
        public string Doors { get; set; }
        public string Allocation_1 { get; set; }
        public string Allocation_1_1 { get; set; }
        public string Quantity_Per_Pack { get; set; }
        public string Number_of_Packs { get; set; }
        public string Description { get; set; }
    }
}
