//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Large_enclosure_myconfig
    {
        public int ID { get; set; }
        public string Config_name { get; set; }
        public string Unique_id { get; set; }
        public System.DateTime Date_created { get; set; }
        public string materials { get; set; }
        public string Username { get; set; }
    }
}
