//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localization
    {
        public int localization_id { get; set; }
        public string table_name { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string column_name { get; set; }
        public string message_original { get; set; }
        public string message_translated { get; set; }
        public Nullable<int> language { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
