//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdf_main
    {
        public long mdf_ID { get; set; }
        public Nullable<long> mdf_user { get; set; }
        public Nullable<long> mdf_SAP { get; set; }
        public Nullable<long> mdf_comp { get; set; }
        public string mdf_title { get; set; }
        public string mdf_desc { get; set; }
        public Nullable<long> mdf_loc { get; set; }
        public Nullable<double> mdf_totalCost { get; set; }
        public Nullable<double> mdf_mdfCost { get; set; }
        public Nullable<System.DateTime> mdf_date { get; set; }
        public Nullable<int> mdf_type { get; set; }
        public Nullable<int> mdf_status { get; set; }
        public string mdf_comments { get; set; }
        public string mdf_comments2 { get; set; }
        public string mdf_comments3 { get; set; }
        public Nullable<System.DateTime> mdf_requestDate { get; set; }
        public Nullable<System.DateTime> mdf_reviewDate { get; set; }
        public Nullable<System.DateTime> mdf_validationDate { get; set; }
        public Nullable<System.DateTime> mdf_creditIssueDate { get; set; }
        public Nullable<double> mdf_approvedAmt { get; set; }
        public Nullable<double> mdf_validatedAmt { get; set; }
        public string mdf_creditMemoNum { get; set; }
        public string mdf_accountingInstruct { get; set; }
        public Nullable<int> archive_year { get; set; }
        public string mdf_requestType { get; set; }
        public string cost_center { get; set; }
        public string rcm { get; set; }
        public Nullable<double> mdf_approvedAmt_mkt { get; set; }
        public Nullable<double> mdf_validatedAmt_mkt { get; set; }
    }
}
