//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mdf_file
    {
        public long mdf_file_ID { get; set; }
        public Nullable<long> mdf_ID { get; set; }
        public string mdf_file_name { get; set; }
        public Nullable<byte> mdf_file_type { get; set; }
    }
}
