//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    [Table("nav1")]
    public partial class Nav1ViewModel
    {
        [Key]
        public int n1ID { get; set; }
        [Display(Name = "Link Order")]
        public Nullable<int> n1order { get; set; }
        [Display(Name = "Short Name")]
        public string n1_nameShort { get; set; }
        [Display(Name = "Long Name")]
        public string n1_nameLong { get; set; }
        [Display(Name = "Link hidden Name")]
        public string linkId { get; set; }
        [Display(Name = "Nav. Page Name")]
        public string pageName { get; set; }
        [Display(Name = "Nav. Controller Name")]
        public string controller { get; set; }
        [Display(Name = "Short Description")]
        public string n1_descShort { get; set; }
        [Display(Name = "Long Description")]
        public string n1_descLong { get; set; }
        [Display(Name = "Nav. Status")]
        public int? n1_active { get; set; }
        [Display(Name = "Edited By")]
        public Nullable<long> n1_editBy { get; set; }
        [Display(Name = "Date Edited")]
        public Nullable<System.DateTime> n1_editDate { get; set; }
        [Display(Name = "Header Image")]
        public string n1_headerImg { get; set; }
        [Display(Name = "Visibility")]
        public string usr_group { get; set; }
        public IEnumerable<rolesList> user_roles { get; set; }
        public List<Nav1Viewlabels> nav1labels { get; set; }
        [Display(Name = "Language")]
        public Nullable<int> default_language { get; set; }
        public IEnumerable<System.Web.Mvc.SelectListItem> list_language_ids { get; set; }
        [Display(Name = "Location")]
        public string locations { get; set; }
        public IEnumerable<Nav1List> list_location_ids { get; set; }
        public List<Nav1Viewlabels> list_nav1_labels { get; set; }
    }

    public class Nav1Viewlabels
    {
        [Key]
        public int n1ID { get; set; }
        public string[] n1order_label { get; set; }
        public string[] n1_nameshort_label { get; set; }
        public string[] n1_nameLong_label { get; set; }
        public string[] linkId_label { get; set; }
        public string[] pageName_label { get; set; }
        public string[] controller_label { get; set; }
        public string[] n1_descShort_label { get; set; }
        public string[] n1_descLong_label { get; set; }
        public string[] n1_active_label { get; set; }
        public string[] n1_editBy_label { get; set; }
        public string[] n1_editDate_label { get; set; }
        public string[] n1_headerImg_label { get; set; }
        public string[] usr_group_label { get; set; }
        public string[] add_link_label { get; set; }
        public string[] edit_label { get; set; }
        public string[] delete_label { get; set; }
        public string[] default_language { get; set; }
        public string[] location { get; set; }
        public string[] active_label { get; set; }
        public string[] not_active_label { get; set; }
        public string[] select_lang_label { get; set; }
        public string[] select_status_label { get; set; }
    }


}