//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nav1
    {
        public int n1ID { get; set; }
        public Nullable<int> n1order { get; set; }
        public string n1_nameShort { get; set; }
        public string n1_nameLong { get; set; }
        public string linkId { get; set; }
        public string pageName { get; set; }
        public string controller { get; set; }
        public string n1_descShort { get; set; }
        public string n1_descLong { get; set; }
        public Nullable<long> n1_editBy { get; set; }
        public Nullable<System.DateTime> n1_editDate { get; set; }
        public string n1_headerImg { get; set; }
        public string usr_group { get; set; }
        public Nullable<int> n1_active { get; set; }
        public Nullable<int> default_language { get; set; }
        public string locations { get; set; }
    }
}
