//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nav2
    {
        public long n2ID { get; set; }
        public Nullable<int> n1ID { get; set; }
        public Nullable<int> n2order { get; set; }
        public string n2_nameShort { get; set; }
        public string n2_nameLong { get; set; }
        public string PageName { get; set; }
        public string Controller { get; set; }
        public string n2_descShort { get; set; }
        public string n2_descLong { get; set; }
        public string n2_descLongAlt { get; set; }
        public Nullable<int> n2_active { get; set; }
        public string n2_products { get; set; }
        public string n2_usrTypes { get; set; }
        public Nullable<long> n2_editBy { get; set; }
        public Nullable<System.DateTime> n2_editDate { get; set; }
        public string n2_headerImg { get; set; }
        public string n2_redirect { get; set; }
        public string n2_redirectJS { get; set; }
        public string n2_keywords { get; set; }
        public Nullable<long> old_n3id { get; set; }
        public Nullable<long> old_n2id { get; set; }
        public string n2_industry { get; set; }
        public Nullable<long> n2_IT_approver { get; set; }
        public Nullable<long> n2_IE_approver { get; set; }
        public string usr_group { get; set; }
        public Nullable<int> default_language { get; set; }
    }
}
