//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.ComponentModel.DataAnnotations.Schema;

namespace newrisourcecenter.Models
{
    [Table("nav2")]
    public class Nav2ViewModel
    {
        [Key]
        public long n2ID { get; set; }
        [Display(Name = "Select Top Nav.")]
        public Nullable<int> n1ID { get; set; }
        public IEnumerable<System.Web.Mvc.SelectListItem> list_n1ID { get; set; }
        [Display(Name = "Nav Order")]
        public Nullable<int> n2order { get; set; }
        [Display(Name = "Short Name")]
        public string n2_nameShort { get; set; }
        [Display(Name = "Long Name")]
        public string n2_nameLong { get; set; }
        [Display(Name = "Short Description")]
        public string n2_descShort { get; set; }
        [AllowHtml]
        [Display(Name = "Long Description")]
        public string n2_descLong { get; set; }
        [Display(Name = "Alternative Description")]
        [AllowHtml]
        public string n2_descLongAlt { get; set; }
        [Display(Name = "Nav 2 Status")]
        public Nullable<int> n2_active { get; set; }
        [Display(Name = "Select Products")]
        public string n2_products { get; set; }
        public IEnumerable<partnerProduct> list_products { get; set; }
        [Display(Name = "Select Audience")]
        public string n2_usrTypes { get; set; }
        public IEnumerable<partnerType> list_Type { get; set; }
        [Display(Name = "Edited By")]
        public Nullable<long> n2_editBy { get; set; }
        [Display(Name = "Edited Date")]
        public Nullable<System.DateTime> n2_editDate { get; set; }
        [Display(Name = "Header Image")]
        public string n2_headerImg { get; set; }
        public IEnumerable<risourcesTypeViewModel> risource_icon { get; set; }
        [Display(Name = "Redirect Link")]
        public string n2_redirect { get; set; }
        public string n2_redirectJS { get; set; }
        public string n2_keywords { get; set; }
        public Nullable<long> old_n3id { get; set; }
        public Nullable<long> old_n2id { get; set; }
        [Display(Name = "Industry")]
        public string n2_industry { get; set; }
        public IEnumerable<partnerIndustry> list_industry { get; set; }
        [Display(Name = "IT Approver")]
        public Nullable<long> n2_IT_approver { get; set; }
        [Display(Name = "IE Approver")]
        public Nullable<long> n2_IE_approver { get; set; }
        [Display(Name = "Page Name")]
        public string PageName { get; set; }
        [Display(Name = "Controller Name")]
        public string Controller { get; set; }
        [Display(Name = "Visibility")]
        public string usr_group { get; set; }
        public IEnumerable<usr_user> list_user { get; set; }
        public IEnumerable<rolesList> user_roles { get; set; }
        public List<Nav2Viewlabels> nav2labels { get; set; }
    }

    public class rolesList
    {
        public string id { get; set; }
        public string[] name { get; set; }
    }

    public class Nav2Viewlabels
    {
        [Key]
        public long n2ID { get; set; }
        public string[] n1ID_label { get; set; }
        public string[] n2order_label { get; set; }
        public string[] n2_nameShort_label { get; set; }
        public string[] n2_nameLong_label { get; set; }
        public string[] n2_descShort_label { get; set; }
        public string[] n2_descLong_label { get; set; }
        public string[] n2_descLongAlt_label { get; set; }
        public string[] n2_active_label { get; set; }
        public string[] n2_products_label { get; set; }
        public string[] n2_usrTypes_label { get; set; }
        public string[] n2_editBy_label { get; set; }
        public string[] n2_headerImg_label { get; set; }
        public string[] n2_redirect_label { get; set; }
        public string[] n2_redirectJS_label { get; set; }
        public string[] n2_keywords_label { get; set; }
        public string[] old_n3id_label { get; set; }
        public string[] old_n2id_label { get; set; }
        public string[] n2_industry_label { get; set; }
        public string[] n2_IT_approver_label { get; set; }
        public string[] n2_IE_approver_label { get; set; }
        public string[] PageName_label { get; set; }
        public string[] Controller_label { get; set; }
        public string[] usr_group_label { get; set; }
        public string[] add_link_label { get; set;}
        public string[] filter_link_label { get; set; }
        public string[] edit_label { get; set; }
        public string[] delete_label { get; set; }
    }

}