//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nav3
    {
        public long n3ID { get; set; }
        public Nullable<long> n2ID { get; set; }
        public Nullable<int> n3order { get; set; }
        public string n3_nameShort { get; set; }
        public string n3_nameLong { get; set; }
        public string n3_descShort { get; set; }
        public string n3_descLong { get; set; }
        public Nullable<int> n3_active { get; set; }
        public string n3_products { get; set; }
        public string n3_usrTypes { get; set; }
        public Nullable<long> n3_editBy { get; set; }
        public Nullable<System.DateTime> n3_editDate { get; set; }
        public string n3_redirect { get; set; }
        public string n3_keywords { get; set; }
        public string n3_industry { get; set; }
        public Nullable<long> old_n3id { get; set; }
        public Nullable<long> old_n2id { get; set; }
        public Nullable<int> default_language { get; set; }
        public string file_name { get; set; }
    }
}
