//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerLocation
    {
        public long loc_ID { get; set; }
        public Nullable<long> comp_ID { get; set; }
        public string loc_name { get; set; }
        public string loc_add1 { get; set; }
        public string loc_add2 { get; set; }
        public string loc_city { get; set; }
        public string loc_state { get; set; }
        public string loc_zip { get; set; }
        public string loc_phone { get; set; }
        public string loc_fax { get; set; }
        public string loc_web { get; set; }
        public string loc_email { get; set; }
        public string loc_logo { get; set; }
        public Nullable<double> loc_lat { get; set; }
        public Nullable<double> loc_lon { get; set; }
        public Nullable<byte> loc_dealor_status { get; set; }
        public Nullable<byte> loc_show_address { get; set; }
        public Nullable<long> loc_SAP_account { get; set; }
        public string loc_SAP_password { get; set; }
        public Nullable<System.DateTime> loc_dateCreated { get; set; }
        public Nullable<System.DateTime> loc_dateUpdated { get; set; }
        public Nullable<long> loc_createdBy { get; set; }
        public Nullable<long> loc_updatedBy { get; set; }
        public Nullable<long> old_locID { get; set; }
        public string price_group { get; set; }
        public string loc_Webshop_account { get; set; }
        public string loc_Webshop_password { get; set; }
    }
}
