//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerStockCheck
    {
        public long ps_ID { get; set; }
        public Nullable<long> ps_account { get; set; }
        public Nullable<int> usr_user { get; set; }
        public Nullable<long> loc_id { get; set; }
    }
}
