//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class partnerCompany
    {
        public long comp_ID { get; set; }
        public string comp_name { get; set; }
        public Nullable<byte> comp_industry { get; set; }
        public Nullable<byte> comp_type { get; set; }
        public Nullable<byte> comp_level { get; set; }
        public string comp_products { get; set; }
        public Nullable<byte> comp_SAP { get; set; }
        public Nullable<byte> comp_POS { get; set; }
        public Nullable<byte> comp_SPA { get; set; }
        public Nullable<byte> comp_project_reg { get; set; }
        public Nullable<byte> comp_MDF { get; set; }
        public Nullable<double> comp_MDF_amount { get; set; }
        public Nullable<double> comp_MDF_tLimit { get; set; }
        public Nullable<double> comp_MDF_aLimit { get; set; }
        public Nullable<double> comp_MDF_eLimit { get; set; }
        public Nullable<double> comp_MDF_dLimit { get; set; }
        public Nullable<double> comp_MDF_mLimit { get; set; }
        public Nullable<double> comp_MDF_oLimit { get; set; }
        public Nullable<byte> comp_FX { get; set; }
        public Nullable<byte> comp_active { get; set; }
        public Nullable<System.DateTime> comp_dateCreated { get; set; }
        public Nullable<System.DateTime> comp_dateUpdated { get; set; }
        public Nullable<long> comp_createdBy { get; set; }
        public Nullable<long> comp_updatedBy { get; set; }
        public Nullable<long> old_ID { get; set; }
        public Nullable<int> comp_RiCRM { get; set; }
        public string comp_region { get; set; }
        public Nullable<double> comp_MDF_rLimit { get; set; }
        public Nullable<double> comp_MDF_trLimit { get; set; }
        public Nullable<double> comp_MDF_rtLimit { get; set; }
        public Nullable<double> comp_MDF_sLimit { get; set; }
        public Nullable<byte> bid_registration { get; set; }
        public string it_territory_manager { get; set; }
        public string it_director { get; set; }
        public string general_manager { get; set; }
        public Nullable<double> comp_MKT_Limit { get; set; }
    }
}
