//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMQuote
    {
        public int ID { get; set; }
        public string company_name { get; set; }
        public string contact_name { get; set; }
        public string street_address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public string manager_name { get; set; }
        public string title { get; set; }
        public string email { get; set; }
        public Nullable<short> heat_exchanger { get; set; }
        public Nullable<short> ac { get; set; }
        public Nullable<short> lcp_cw { get; set; }
        public Nullable<short> chiller { get; set; }
        public Nullable<short> lcp_dx { get; set; }
        public Nullable<short> lcp_dx_condenser { get; set; }
        public Nullable<short> det_ac { get; set; }
        public string enviromental_conditions { get; set; }
        public System.DateTime submitted_on { get; set; }
        public string file_url { get; set; }
        public Nullable<int> submitted_by { get; set; }
        public string service_type { get; set; }
    }
}
