//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string part_number { get; set; }
        public string enclosure_type { get; set; }
        public string family { get; set; }
        public string material { get; set; }
        public Nullable<short> width { get; set; }
        public Nullable<short> height { get; set; }
        public Nullable<short> depth { get; set; }
        public string rating { get; set; }
        public string door { get; set; }
        public string additional_information { get; set; }
        public string product_type { get; set; }
        public string industry { get; set; }
        public string color { get; set; }
    }
}
