//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuizOption()
        {
            this.TrainingQuizAttemptAnswers = new HashSet<TrainingQuizAttemptAnswer>();
        }
    
        public int Id { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string OptionText { get; set; }
        public bool IsCorrect { get; set; }
    
        public virtual QuizQuestion QuizQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingQuizAttemptAnswer> TrainingQuizAttemptAnswers { get; set; }
    }
}
