//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnToolExtention
    {
        public int ext_id { get; set; }
        public Nullable<int> form_id { get; set; }
        public string return_type { get; set; }
        public string part_num { get; set; }
        public Nullable<int> quantity { get; set; }
        public string quote_num { get; set; }
        public string return_reason { get; set; }
        public string reasoncheckbox { get; set; }
        public string po_num { get; set; }
        public string partpo_num { get; set; }
    }
}
