//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnTool
    {
        public int form_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> admin_id { get; set; }
        public string po_num { get; set; }
        public string sap_num { get; set; }
        public Nullable<System.DateTime> request_date { get; set; }
        public Nullable<System.DateTime> submission_date { get; set; }
        public Nullable<System.DateTime> completion_date { get; set; }
        public string status { get; set; }
        public string location { get; set; }
        public string admin_notes { get; set; }
        public string return_type { get; set; }
        public string warranty { get; set; }
    }
}
