//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnToolActionLog
    {
        public int log_id { get; set; }
        public Nullable<int> form_id { get; set; }
        public int user_id { get; set; }
        public string action { get; set; }
        public Nullable<System.DateTime> action_time { get; set; }
        public string notes { get; set; }
        public string authNumber { get; set; }
    }
}
