//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnToolFile
    {
        public int file_id { get; set; }
        public Nullable<int> form_id { get; set; }
        public string return_type { get; set; }
        public string file_name { get; set; }
        public string identifier { get; set; }
        public string offset_po { get; set; }
    }
}
