//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQ_RAS_Data
    {
        public int ID { get; set; }
        public string account_manager { get; set; }
        public string regional_manager { get; set; }
        public string machine_type { get; set; }
        public string competitor { get; set; }
        public Nullable<int> opportunity_id { get; set; }
        public Nullable<int> erp_id { get; set; }
        public string company { get; set; }
        public string contact_name { get; set; }
        public string phone_number { get; set; }
        public string email { get; set; }
        public string street_address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zipcode { get; set; }
        public string delivery_type { get; set; }
        public string transformer_voltage { get; set; }
        public string equipment_options { get; set; }
    }
}
