//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQ_Data
    {
        public int ID { get; set; }
        public string sales_engineer { get; set; }
        public string regional_director { get; set; }
        public string cell_phone { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> submission_date { get; set; }
        public string updated_quote { get; set; }
        public string sold_to_party { get; set; }
        public string qte_num { get; set; }
        public string sap_account_num { get; set; }
        public string location { get; set; }
        public string end_contact { get; set; }
        public string opportunity_num { get; set; }
        public string qte_ref { get; set; }
        public string qte_description { get; set; }
        public string draw_num { get; set; }
        public string total_qty { get; set; }
        public string release_qty { get; set; }
        public string competition { get; set; }
        public string target_price { get; set; }
        public string scale_volume { get; set; }
        public string spa_contract_num { get; set; }
        public string spa_mult { get; set; }
        public Nullable<short> drawing_approval { get; set; }
        public string product_category { get; set; }
        public string xpress_mod_data { get; set; }
        public string xpress_mod_non_data { get; set; }
        public string enclosure_type_it { get; set; }
        public string part_num_it { get; set; }
        public string size_hxwxd_it { get; set; }
        public string color_it { get; set; }
        public string sidewall_style_it { get; set; }
        public string sidewall_location_it { get; set; }
        public string castors_it { get; set; }
        public string Leveling_feet_it { get; set; }
        public string front_it { get; set; }
        public string rear_it { get; set; }
        public string cable_it { get; set; }
        public string handles_it { get; set; }
        public string inserts_it { get; set; }
        public string partition_wall_it { get; set; }
        public string baffles_it { get; set; }
        public string bsaying_brackets_it { get; set; }
        public string additional_info_datacenter { get; set; }
        public string intell_data { get; set; }
        public string voltage_data { get; set; }
        public string amp_data { get; set; }
        public string outlet_it { get; set; }
        public string quantity_type_data { get; set; }
        public string input_cord_it { get; set; }
        public string expansion_it { get; set; }
        public string part_num_ie { get; set; }
        public string size_hxwxd_ie { get; set; }
        public string material_ie { get; set; }
        public string mpl_ie { get; set; }
        public string sidewall_ie { get; set; }
        public string front_ie { get; set; }
        public string rear_ie { get; set; }
        public string plinths_ie { get; set; }
        public string cable_ie { get; set; }
        public string handles_ie { get; set; }
        public string inserts_ie { get; set; }
        public string Rails { get; set; }
        public string Suited { get; set; }
        public string suited_bay_ie { get; set; }
        public string door_ie { get; set; }
        public string roof_ie { get; set; }
        public string rear_wall_ie { get; set; }
        public string sidewall_mod_ie { get; set; }
        public string mpl_mod_ie { get; set; }
        public string special_paint_ie { get; set; }
        public string specialpaint_ie_1 { get; set; }
        public string color_mod_ie { get; set; }
        public string ul_nema_other_ie { get; set; }
        public string rating_ie { get; set; }
        public string part_num_WM_AE_JB { get; set; }
        public string size_hxwxd_WM_AE_JB { get; set; }
        public string material_WM_AE_JB { get; set; }
        public string mpl_WM_AE_JB { get; set; }
        public string latching_wm { get; set; }
        public string body_modified_wm { get; set; }
        public string door_modified_wm { get; set; }
        public string mpl_modified_wm { get; set; }
        public string special_paint_wm { get; set; }
        public string specialpaint_wm_1 { get; set; }
        public string color_WM_AE_JB { get; set; }
        public string ul_nema_WM_AE_JB { get; set; }
        public string rating_WM_AE_JB { get; set; }
        public string part_num_other_1 { get; set; }
        public string size_hxwxd_other_1 { get; set; }
        public string producttype_other_1 { get; set; }
        public string material_other_1 { get; set; }
        public string body_modified_other_1 { get; set; }
        public string door_modified_other_1 { get; set; }
        public string mpl_modified_other_1 { get; set; }
        public string specialpaint_other_1 { get; set; }
        public string specialpaint_other { get; set; }
        public string color_mod_other { get; set; }
        public string ul_nema_other_1 { get; set; }
        public string rating_other_1 { get; set; }
        public string additional_info_footer { get; set; }
        public string qty_installed_1 { get; set; }
        public string part_number_installed_1 { get; set; }
        public string description_installeed_1 { get; set; }
        public string qty_installed_2 { get; set; }
        public string part_number_installed_2 { get; set; }
        public string description_installeed_2 { get; set; }
        public string qty_installed_3 { get; set; }
        public string part_number_installed_3 { get; set; }
        public string description_installeed_3 { get; set; }
        public string qty_shipped_1 { get; set; }
        public string part_number_shipped_1 { get; set; }
        public string description_shipped_1 { get; set; }
        public string qty_shipped_2 { get; set; }
        public string part_number_shipped_2 { get; set; }
        public string description_shipped_2 { get; set; }
        public string qty_shipped_3 { get; set; }
        public string part_number_shipped_3 { get; set; }
        public string description_shipped_3 { get; set; }
        public string send { get; set; }
        public string fileupload { get; set; }
        public Nullable<int> user_id { get; set; }
        public string save { get; set; }
        public string distro_name { get; set; }
        public string distro_company { get; set; }
        public string Quote_Num { get; set; }
        public Nullable<System.DateTime> completion_date { get; set; }
        public string admin_status { get; set; }
        public string plinths_type_ie { get; set; }
        public string deal_registration { get; set; }
        public string end_user { get; set; }
        public Nullable<short> check_project { get; set; }
        public string account_manager { get; set; }
        public string mods_it { get; set; }
        public string mods_ie { get; set; }
        public string mods_other { get; set; }
        public string mods_WM_AE_JB { get; set; }
        public Nullable<short> special_dimension_WM_AE_JB { get; set; }
        public Nullable<short> special_dimension_it { get; set; }
        public Nullable<short> special_dimension_ie { get; set; }
        public Nullable<short> special_dimension_other { get; set; }
        public Nullable<short> suited_enclosures_it { get; set; }
        public Nullable<short> suited_enclosures_ie { get; set; }
        public string enclosure_1_it { get; set; }
        public string enclosure_2_it { get; set; }
        public string enclosure_3_it { get; set; }
        public string enclosure_4_it { get; set; }
        public string enclosure_5_it { get; set; }
        public string enclosure_1_ie { get; set; }
        public string enclosure_2_ie { get; set; }
        public string enclosure_3_ie { get; set; }
        public string enclosure_4_ie { get; set; }
        public string enclosure_5_ie { get; set; }
        public string part_type_it { get; set; }
        public string part_type_ie { get; set; }
        public string part_type_other { get; set; }
        public string part_type_WM_AE_JB { get; set; }
        public string end_user_name { get; set; }
        public string end_user_location { get; set; }
    }
}
