//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQ_Basic_Info
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Submission_Date { get; set; }
        public Nullable<System.DateTime> Completion_Date { get; set; }
        public string Status { get; set; }
        public Nullable<int> Admin_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public string Quote_Num { get; set; }
        public string Admin_Notes { get; set; }
        public string Sales_Engineer { get; set; }
        public string Sold_to_Party { get; set; }
        public string End_User { get; set; }
        public string Image_Name { get; set; }
    }
}
