//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQ_Parts_Installed
    {
        public int id { get; set; }
        public Nullable<int> form_id { get; set; }
        public Nullable<int> ext_form_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string qty_installed { get; set; }
        public string part_number_installed { get; set; }
        public string description_installed { get; set; }
    }
}
