//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQ_New_Action_Log
    {
        public int ID { get; set; }
        public Nullable<int> Form_ID { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> Action_Time { get; set; }
        public string Notes { get; set; }
        public string Usr_ID { get; set; }
        public string Admin_ID { get; set; }
    }
}
