//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RisourceCenterMexicoEntities : DbContext
    {
        public RisourceCenterMexicoEntities()
            : base("name=RisourceCenterMexicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<literature_requested> literature_requested { get; set; }
        public virtual DbSet<nav3> nav3 { get; set; }
        public virtual DbSet<partnerProduct> partnerProducts { get; set; }
        public virtual DbSet<RiSources_Action_Log> RiSources_Action_Log { get; set; }
        public virtual DbSet<ReturnToolActionLog> ReturnToolActionLogs { get; set; }
        public virtual DbSet<mdf_subType> mdf_subType { get; set; }
        public virtual DbSet<ReturnTool> ReturnTools { get; set; }
        public virtual DbSet<RFQ_Parts_Installed> RFQ_Parts_Installed { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<adminPerm> adminPerms { get; set; }
        public virtual DbSet<Announcement_logs> Announcement_logs { get; set; }
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CountLoggedin> CountLoggedins { get; set; }
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<data_state> data_state { get; set; }
        public virtual DbSet<email_tracker> email_tracker { get; set; }
        public virtual DbSet<Label> Labels { get; set; }
        public virtual DbSet<Large_enclosure_fmd> Large_enclosure_fmd { get; set; }
        public virtual DbSet<Large_enclosure_myaccessories> Large_enclosure_myaccessories { get; set; }
        public virtual DbSet<Large_enclosure_myconfig> Large_enclosure_myconfig { get; set; }
        public virtual DbSet<Large_enclosure_pricing> Large_enclosure_pricing { get; set; }
        public virtual DbSet<Large_enclosure_ts8> Large_enclosure_ts8 { get; set; }
        public virtual DbSet<literature> literatures { get; set; }
        public virtual DbSet<Localization> Localizations { get; set; }
        public virtual DbSet<mdf_file> mdf_file { get; set; }
        public virtual DbSet<mdf_main> mdf_main { get; set; }
        public virtual DbSet<mdf_type> mdf_type { get; set; }
        public virtual DbSet<nav1> nav1 { get; set; }
        public virtual DbSet<nav2> nav2 { get; set; }
        public virtual DbSet<PartnerApplication> PartnerApplications { get; set; }
        public virtual DbSet<partnerCompany_Archive> partnerCompany_Archive { get; set; }
        public virtual DbSet<partnerIndustry> partnerIndustries { get; set; }
        public virtual DbSet<partnerLocation> partnerLocations { get; set; }
        public virtual DbSet<partnerType> partnerTypes { get; set; }
        public virtual DbSet<ReturnToolExtention> ReturnToolExtentions { get; set; }
        public virtual DbSet<ReturnToolFile> ReturnToolFiles { get; set; }
        public virtual DbSet<RFQ_Action_Log> RFQ_Action_Log { get; set; }
        public virtual DbSet<RFQ_Data> RFQ_Data { get; set; }
        public virtual DbSet<RFQ_Data_Extend> RFQ_Data_Extend { get; set; }
        public virtual DbSet<RFQ_Files> RFQ_Files { get; set; }
        public virtual DbSet<RFQ_Parts_Shipped> RFQ_Parts_Shipped { get; set; }
        public virtual DbSet<RiSourceCart> RiSourceCarts { get; set; }
        public virtual DbSet<RiSource> RiSources { get; set; }
        public virtual DbSet<risourcesCategory> risourcesCategories { get; set; }
        public virtual DbSet<risourcesType_image> risourcesType_image { get; set; }
        public virtual DbSet<salesComm> salesComms { get; set; }
        public virtual DbSet<salesRequest> salesRequests { get; set; }
        public virtual DbSet<salesRequest_Action_Log> salesRequest_Action_Log { get; set; }
        public virtual DbSet<salesRequest_Additional_Info> salesRequest_Additional_Info { get; set; }
        public virtual DbSet<salesRequest_Approvers> salesRequest_Approvers { get; set; }
        public virtual DbSet<salesRequest_File> salesRequest_File { get; set; }
        public virtual DbSet<SiteActionLogModel> SiteActionLogModels { get; set; }
        public virtual DbSet<SiteApprover> SiteApprovers { get; set; }
        public virtual DbSet<SPA_Account_Manager> SPA_Account_Manager { get; set; }
        public virtual DbSet<SPA_FIles> SPA_FIles { get; set; }
        public virtual DbSet<SPA_Intostock_Multiplier> SPA_Intostock_Multiplier { get; set; }
        public virtual DbSet<SPA_Material_Master> SPA_Material_Master { get; set; }
        public virtual DbSet<SPA_Notes> SPA_Notes { get; set; }
        public virtual DbSet<SPA_Rebates> SPA_Rebates { get; set; }
        public virtual DbSet<SPA_RebatesItems> SPA_RebatesItems { get; set; }
        public virtual DbSet<SPA_SalesReps> SPA_SalesReps { get; set; }
        public virtual DbSet<SPA_Territory_Codes> SPA_Territory_Codes { get; set; }
        public virtual DbSet<SPAItem> SPAItems { get; set; }
        public virtual DbSet<SPA> SPAs { get; set; }
        public virtual DbSet<SPASku> SPASkus { get; set; }
        public virtual DbSet<stats_training> stats_training { get; set; }
        public virtual DbSet<theme> themes { get; set; }
        public virtual DbSet<usr_user> usr_user { get; set; }
        public virtual DbSet<usr_user_temp> usr_user_temp { get; set; }
        public virtual DbSet<usr_user_test> usr_user_test { get; set; }
        public virtual DbSet<Webshop_connect> Webshop_connect { get; set; }
        public virtual DbSet<partnerCompany> partnerCompanies { get; set; }
        public virtual DbSet<partnerStockCheck> partnerStockChecks { get; set; }
        public virtual DbSet<ChangeCommission> ChangeCommissions { get; set; }
        public virtual DbSet<ChangeCommissionPart> ChangeCommissionParts { get; set; }
        public virtual DbSet<ChangeCommissionHistory> ChangeCommissionHistories { get; set; }
        public virtual DbSet<CommissionAdmin> CommissionAdmins { get; set; }
        public virtual DbSet<RFQ_RAS_Data> RFQ_RAS_Data { get; set; }
        public virtual DbSet<RCMContact> RCMContacts { get; set; }
        public virtual DbSet<BidRegistration> BidRegistrations { get; set; }
        public virtual DbSet<PMQuote> PMQuotes { get; set; }
        public virtual DbSet<mdf_pinnacle_file> mdf_pinnacle_file { get; set; }
        public virtual DbSet<mdf_pinnacle_main> mdf_pinnacle_main { get; set; }
        public virtual DbSet<RegionApprover> RegionApprovers { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<product_accessories> product_accessories { get; set; }
        public virtual DbSet<ac_products> ac_products { get; set; }
        public virtual DbSet<fan_filters> fan_filters { get; set; }
        public virtual DbSet<fan_products> fan_products { get; set; }
        public virtual DbSet<heat_exchangers> heat_exchangers { get; set; }
        public virtual DbSet<accessory> accessories { get; set; }
        public virtual DbSet<RFQ_New_Action_Log> RFQ_New_Action_Log { get; set; }
        public virtual DbSet<RFQ_New_Data> RFQ_New_Data { get; set; }
        public virtual DbSet<RFQ_New_Data_Extend> RFQ_New_Data_Extend { get; set; }
        public virtual DbSet<RFQ_New_Files> RFQ_New_Files { get; set; }
        public virtual DbSet<trainingClass> trainingClasses { get; set; }
        public virtual DbSet<trainingTrack> trainingTracks { get; set; }
        public virtual DbSet<usrClass> usrClasses { get; set; }
    }
}
