//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiSource
    {
        public int ris_ID { get; set; }
        public Nullable<long> n2ID { get; set; }
        public Nullable<long> n3ID { get; set; }
        public string ris_headline { get; set; }
        public string ris_teaser { get; set; }
        public string ris_body { get; set; }
        public string ris_status { get; set; }
        public string ris_keywords { get; set; }
        public string ris_products { get; set; }
        public string ris_industry { get; set; }
        public string ris_usrTypes { get; set; }
        public string ris_categories { get; set; }
        public string ris_editedBy { get; set; }
        public string ris_owner { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public string ris_link { get; set; }
        public string file_size { get; set; }
        public string file_type { get; set; }
        public Nullable<int> ris_order { get; set; }
        public Nullable<System.DateTime> ris_startDate { get; set; }
        public Nullable<System.DateTime> ris_endDate { get; set; }
        public string displayimage { get; set; }
        public string ris_partnerApp { get; set; }
    }
}
