//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_wins_comments
    {
        public long win_comment_id { get; set; }
        public long win_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime win_comment_date { get; set; }
        public string win_comment { get; set; }
        public string usr_fName { get; set; }
        public string usr_lName { get; set; }
        public string usr_email { get; set; }
    }
}
