//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesRequest_Additional_Info
    {
        public int ID { get; set; }
        public int Form_ID { get; set; }
        public string quantity { get; set; }
        public string achType { get; set; }
        public string cccType { get; set; }
        public string partNumberOrdescription { get; set; }
        public string deliveryDate { get; set; }
        public string unitPrice { get; set; }
        public string totalPrice { get; set; }
    }
}
