//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesRequest_File
    {
        public int ID { get; set; }
        public int FormID { get; set; }
        public string fileName { get; set; }
        public int AttachmentType { get; set; }
    }
}
