//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_wins
    {
        public long win_id { get; set; }
        public int user_id { get; set; }
        public decimal win_amount { get; set; }
        public long win_amount_projected { get; set; }
        public System.DateTime win_date { get; set; }
        public string win_type { get; set; }
        public string win_lead { get; set; }
        public string win_competitor { get; set; }
        public string win_product { get; set; }
        public bool win_case_study { get; set; }
        public string win_customer { get; set; }
        public string win_message { get; set; }
        public string usr_fName { get; set; }
        public string usr_lName { get; set; }
        public string usr_email { get; set; }
    }
}
