//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesRequest
    {
        public int FormID { get; set; }
        public Nullable<long> SalesRepID { get; set; }
        public string paymentMethod { get; set; }
        public string department { get; set; }
        public string requestType { get; set; }
        public string supplier { get; set; }
        public string shipTo { get; set; }
        public string supplierNumber { get; set; }
        public string shiptoAttn { get; set; }
        public string partNumberDescription { get; set; }
        public string estimatedTotalCost { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public string region { get; set; }
        public string ponumber { get; set; }
        public Nullable<int> compID { get; set; }
        public Nullable<System.DateTime> dateCompleted { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string estimatedCost { get; set; }
        public Nullable<System.DateTime> activitydate { get; set; }
        public int InvoiceAmountIsEqual { get; set; }
    }
}
