//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesComm
    {
        public long scID { get; set; }
        public Nullable<long> n2ID { get; set; }
        public Nullable<long> n3ID { get; set; }
        public Nullable<int> sc_status { get; set; }
        public string sc_headline { get; set; }
        public string sc_teaser { get; set; }
        public string sc_body { get; set; }
        public string sc_keywords { get; set; }
        public string sc_products { get; set; }
        public string sc_usrTypes { get; set; }
        public Nullable<System.DateTime> sc_startDate { get; set; }
        public Nullable<System.DateTime> sc_endDate { get; set; }
        public Nullable<long> sc_owner { get; set; }
        public string sc_industry { get; set; }
        public Nullable<long> old_scid { get; set; }
        public string attach_risource { get; set; }
        public string countries { get; set; }
        public Nullable<int> default_lang { get; set; }
        public string languages { get; set; }
        public Nullable<System.DateTime> submission_date { get; set; }
    }
}
