//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesRequest_Approvers
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string regionName { get; set; }
        public Nullable<int> status { get; set; }
        public string Department { get; set; }
    }
}
