//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sku
    {
        public int Sku_id { get; set; }
        public string Description { get; set; }
        public int ListPrice { get; set; }
        public int IntoStockPrice { get; set; }
        public int Cost { get; set; }
        public int IntoStockMultiplier { get; set; }
        public int Sku_code { get; set; }
    }
}
