//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPA
    {
        public int Spa_id { get; set; }
        public Nullable<int> Usr_id { get; set; }
        public Nullable<int> Comp_id { get; set; }
        public string Customer_name { get; set; }
        public string Customer_address1 { get; set; }
        public string Customer_address2 { get; set; }
        public string Customer_city { get; set; }
        public string Customer_state { get; set; }
        public string Customer_zip { get; set; }
        public string Customer_phone { get; set; }
        public string Customer_email { get; set; }
        public string Customer_title { get; set; }
        public Nullable<System.DateTime> Start_date { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
        public Nullable<System.DateTime> Updated_date { get; set; }
        public Nullable<System.DateTime> Approved_date { get; set; }
        public Nullable<int> Updated_by { get; set; }
        public string Projected_sales { get; set; }
        public string Competition { get; set; }
        public string Territory_code { get; set; }
        public string Activity_status { get; set; }
        public string Status { get; set; }
        public string Contract_type { get; set; }
        public string Market_segement { get; set; }
        public string Account_type { get; set; }
        public string Contract_id { get; set; }
        public string Customer_company_name { get; set; }
        public string Additional_information { get; set; }
        public string Distributor_location { get; set; }
        public string Sales_rep_user { get; set; }
        public string Customer_fax { get; set; }
    }
}
