//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPA_Intostock_Multiplier
    {
        public int ID { get; set; }
        public string GG { get; set; }
        public string PG { get; set; }
        public string CC { get; set; }
        public string AA { get; set; }
    }
}
