//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPA_RebatesItems
    {
        public int rebateItem_ID { get; set; }
        public Nullable<int> rebate_ID { get; set; }
        public Nullable<int> contract_ID { get; set; }
        public string sku { get; set; }
        public Nullable<double> last_price { get; set; }
        public Nullable<double> spa_price { get; set; }
        public Nullable<int> quantity_rebated { get; set; }
        public Nullable<int> quantity_requested { get; set; }
        public string capping_status { get; set; }
        public string current_rebate { get; set; }
        public string distributor_requests { get; set; }
        public string original_difference { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public string rebate_amount { get; set; }
        public string reason { get; set; }
        public string status { get; set; }
        public string customer_invoice_number { get; set; }
        public string rittal_invoice_number { get; set; }
    }
}
