//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPA_FIles
    {
        public int File_id { get; set; }
        public Nullable<int> Form_id { get; set; }
        public string File_name { get; set; }
        public string File_ext { get; set; }
    }
}
