//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPA_Territory_Codes
    {
        public int ID { get; set; }
        public string zip_region { get; set; }
        public string zip { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string county { get; set; }
        public string zip_type { get; set; }
        public string ie_sales_office { get; set; }
        public string ie_manager { get; set; }
        public string territory_code { get; set; }
    }
}
