//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPA_Notes
    {
        public int ID { get; set; }
        public bool Note_Type { get; set; }
        public int Form_ID { get; set; }
        public string Action { get; set; }
        public System.DateTime Action_Time { get; set; }
        public string Note { get; set; }
        public int User_ID { get; set; }
    }
}
