//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPA_Rebates
    {
        public int rebate_ID { get; set; }
        public Nullable<int> contract_ID { get; set; }
        public string rebate_total_amount { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> submit_date { get; set; }
        public Nullable<System.DateTime> memo_date { get; set; }
        public string credit_memo { get; set; }
    }
}
