//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPA_Material_Master
    {
        public int ID { get; set; }
        public string material { get; set; }
        public string material_description { get; set; }
        public string mpg { get; set; }
        public string mpg_description { get; set; }
        public string cost { get; set; }
        public string list_price { get; set; }
    }
}
