//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPAItem
    {
        public int Item_id { get; set; }
        public string Product_name { get; set; }
        public int Form_id { get; set; }
        public string Quantity { get; set; }
        public string Sku { get; set; }
        public int Item_Status { get; set; }
        public int Updated_by { get; set; }
        public Nullable<System.DateTime> Date_Created { get; set; }
        public Nullable<System.DateTime> Date_Updated { get; set; }
        public string Requested_price { get; set; }
        public string Requested_multiplier { get; set; }
        public string Target_price { get; set; }
    }
}
