//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stats_training
    {
        public int trid { get; set; }
        public Nullable<long> tr_usr { get; set; }
        public Nullable<System.DateTime> tr_date { get; set; }
        public string tr_module { get; set; }
        public string tr_NumQuestions { get; set; }
        public string tr_PassGrade { get; set; }
        public string tr_score { get; set; }
    }
}
