//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MRK_Zipcode
    {
        public int id { get; set; }
        public string PostalCode { get; set; }
        public string CGrp { get; set; }
        public string V1 { get; set; }
        public string V1Name { get; set; }
        public string V1Email { get; set; }
        public string V1Phone { get; set; }
        public string V6 { get; set; }
        public string V6Name { get; set; }
        public string V6Phone { get; set; }
        public string V6Email { get; set; }
        public string DateImported { get; set; }
    }
}
