//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainingTrack
    {
        public short id { get; set; }
        public string name { get; set; }
        public short complete_days { get; set; }
        public string prize { get; set; }
        public string online_link { get; set; }
        public string person_link { get; set; }
    }
}
