//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingQuizAttempt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainingQuizAttempt()
        {
            this.TrainingQuizAttemptAnswers = new HashSet<TrainingQuizAttemptAnswer>();
        }
    
        public int Id { get; set; }
        public int TrainingContentId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> UserProgressId { get; set; }
        public System.DateTime StartedAt { get; set; }
        public System.DateTime SubmittedAt { get; set; }
        public int TotalQuestions { get; set; }
        public int CorrectQuestions { get; set; }
        public int ScorePercentage { get; set; }
        public int PassingPercentage { get; set; }
        public bool IsPassed { get; set; }
    
        public virtual TrainingContent TrainingContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingQuizAttemptAnswer> TrainingQuizAttemptAnswers { get; set; }
        public virtual UserProgress UserProgress { get; set; }
    }
}
