//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingQuizAttemptAnswer
    {
        public int Id { get; set; }
        public int AttemptId { get; set; }
        public int QuestionId { get; set; }
        public int OptionId { get; set; }
        public bool IsCorrect { get; set; }
    
        public virtual QuizOption QuizOption { get; set; }
        public virtual QuizQuestion QuizQuestion { get; set; }
        public virtual TrainingQuizAttempt TrainingQuizAttempt { get; set; }
    }
}
