//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainingClass
    {
        public int id { get; set; }
        public string category { get; set; }
        public string course_id { get; set; }
        public string course_title { get; set; }
        public Nullable<decimal> duration { get; set; }
        public string link { get; set; }
    }
}
