//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingRoleAssignment
    {
        public int Id { get; set; }
        public int TrainingContentId { get; set; }
        public string RoleId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual TrainingContent TrainingContent { get; set; }
    }
}
