//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProgress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserProgress()
        {
            this.TrainingQuizAttempts = new HashSet<TrainingQuizAttempt>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> TrainingContentId { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> ScorePercentage { get; set; }
        public Nullable<bool> IsPassed { get; set; }
    
        public virtual TrainingContent TrainingContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingQuizAttempt> TrainingQuizAttempts { get; set; }
    }
}
