//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usr_user_test
    {
        public int usr_ID { get; set; }
        public string system_ID { get; set; }
        public string usr_fName { get; set; }
        public string usr_lName { get; set; }
        public string usr_email { get; set; }
        public string usr_password { get; set; }
        public string usr_add1 { get; set; }
        public string usr_add2 { get; set; }
        public string usr_city { get; set; }
        public Nullable<int> usr_state { get; set; }
        public Nullable<int> usr_country { get; set; }
        public Nullable<int> usr_language { get; set; }
        public string usr_zip { get; set; }
        public string usr_phone { get; set; }
        public string usr_fax { get; set; }
        public string usr_web { get; set; }
        public Nullable<byte> usr_role { get; set; }
        public Nullable<byte> usr_SAP { get; set; }
        public Nullable<byte> usr_POS { get; set; }
        public Nullable<byte> usr_SPA { get; set; }
        public Nullable<byte> usr_project_reg { get; set; }
        public Nullable<byte> usr_MDF { get; set; }
        public Nullable<byte> usr_FX { get; set; }
        public Nullable<byte> usr_siteRole { get; set; }
        public Nullable<System.DateTime> usr_dateCreated { get; set; }
        public Nullable<System.DateTime> usr_dateUpdated { get; set; }
        public Nullable<long> comp_ID { get; set; }
        public Nullable<long> comp_loc_ID { get; set; }
        public Nullable<byte> wN { get; set; }
        public Nullable<long> old_usr_id { get; set; }
        public Nullable<long> old_UserID { get; set; }
        public Nullable<System.DateTime> usr_lastLogin { get; set; }
        public Nullable<long> usr_countLogin { get; set; }
        public string usr_title { get; set; }
        public string usr_jigsaw_password { get; set; }
        public Nullable<int> usr_status { get; set; }
        public string usr_jigsaw_login { get; set; }
        public string usr_MDF_login { get; set; }
        public string usr_MDF_password { get; set; }
        public Nullable<int> usr_rfq { get; set; }
        public Nullable<int> usr_RiCRM { get; set; }
        public Nullable<int> admin_theme { get; set; }
        public Nullable<int> show_message { get; set; }
        public string usr_pages { get; set; }
    }
}
