//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newrisourcecenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Webshop_connect
    {
        public int ws_ID { get; set; }
        public string ws_account { get; set; }
        public int usr_user { get; set; }
        public long loc_id { get; set; }
    }
}
