<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<!--GENERATED BY:  Lectora Professional Publishing Suite v.2007 SP5(5100) (http://www.trivantis.com) -->


<head>
<title>title page</title>

<link rel="stylesheet" href="trivantis.css" type="text/css" />
<style text="text/css">
    body { background-color:#ffffff; }
    span.text56Font1 { font-size:16px; font-family:"Arial", sans serif; line-height:19px; color:#000000; font-weight:bold; font-style:italic;}
    span.text56Font2 { font-size:13px; font-family:"Arial", sans serif; line-height:16px; color:#010101;}
    span.text42Font1 { font-size:37px; font-family:"Arial", sans serif; line-height:43px; color:#ffffff;}
</style>

<script language = "JavaScript" src="trivantis.js"></script>
<script language = "JavaScript" src="trivantis-button.js"></script>
<script language = "JavaScript" src="trivantis-image.js"></script>
<script language = "JavaScript" src="trivantis-inline.js"></script>
<script language = "JavaScript" src="trivantis-cookie.js"></script>
<script language = "JavaScript" src="trivantis-timedate.js"></script>
<script language = "JavaScript">

<!-- 
if( !is.min )
    document.write( 'Your browser does not support dynamic html. Please download a current version of either <a href="http://www.microsoft.com/ie/">Microsoft Internet Explorer</a> or <a href="http://www.netscape.com/">Netscape Navigator </a> and try visiting our site again.  Thank You.<br /><br />' )

var pageLayer = null
var winW = screen.width
var winH = screen.height

function findWH() {
    winW = (is.ns)? window.innerWidth-16 : document.body.offsetWidth-20
    winH = (is.ns)? window.innerHeight   : document.body.offsetHeight
}

function ReFlow() {
    if (is.ns4 && winW && (winW!=window.innerWidth-16 || winH!=window.innerHeight))
      ObjLayerActionGoTo( 'index.cfm' )
    else {
      findWH()
      var left = (winW > 785) ? (winW-785)/2 : 0
      if (pageLayer)
      {
        pageLayer.moveTo( left, 0 );
        pageLayer.hasMoved = true;
        pageLayer.newX = left;
        pageLayer.newY = 0;
      }
    }
}


VarCurrentDate = new Variable( 'VarCurrentDate', null, 1, 0, null, null, 'page1' )

onload = init
onunload = finish

function init() {
    findWH()
    if( is.min ){
        setTimeout( "preload( 'images/shape_50.gif','images/image_4026_51.jpg','images/platinum_exitoff.gif','images/platinum_exitclk.gif','images/platinum_exitrol.gif','images/platinum_nextoff.gif','images/platinum_nextclk.gif','images/platinum_nextrol.gif' )", 0 )
        pageLayer = new ObjLayer( 'pageDIV' );
        ReFlow();
        pageLayer.show();
        button61.init()
        button60.init()
        text56.init()
        image39.init()
        text42.init()
        image41.init()
        button61.activate()
        button60.activate()
        text56.activate()
        image39.activate()
        text42.activate()
        image41.activate()
        if( location.hash )
        {
            var newHash
            if( location.hash.charAt(0) == '#' )
                newHash = location.hash.slice( 1 )
            else
                newHash = location.hash
            location.hash = newHash
        }
        setTimeout( 'trivUpdateTOC( "index.cfm", "index.cfm", 1 )', 1000)
    }
}

var trivGoToPage = null
var trivCompleteCnt = 1;
var hasProcessedExitActions = false;
var trivWndFeedback = null;
var currFeedbackIdx = 0;
var trivPageExited = false;

function finish() {
}

function trivOnFocus() {
    if( trivWndFeedback )
    {
      try{if( !trivWndFeedback.closed )
      {
        trivWndFeedback.close()
        trivWndFeedback = null
      }}catch(e){}
      setTimeout( 'checkLeavePage()', 100)
    }
}

function checkLeavePage() {
    if( trivWndFeedback == null || trivWndFeedback.closed )
    {
        trivWndFeedback = null;
        currFeedbackIdx++;
        if( currFeedbackIdx > -1)
        {
            trivLeavePage();
          return;
        }
        else if( !checkQuestions( true ))
          return;
    }
    setTimeout( 'checkLeavePage()', 100)
}

function trivExitPage( newPage, bFeedback ) {
    if( newPage.indexOf( "ObjLayerAction" ) >= 0 || newPage.indexOf( ".action" ) >= 0 || newPage.indexOf( "history.back()" ) >= 0) trivGoToPage = newPage
    else trivGoToPage = 'ObjLayerActionGoTo("' + newPage + '")'
    if( !hasProcessedExitActions ) {
        findWH()
        hasProcessedExitActions = true
        setTimeout( 'checkLeavePage()', 100)
    }
}

function trivLeavePage() {
    trivCompleteCnt--
    if( trivCompleteCnt <= 0 ) {
        hasProcessedExitActions = false
        eval( trivGoToPage )
        trivGoToPage = null;
        trivPageExited = true;
    }
}

function trivPrevPage() {
}

function trivNextPage() {
    trivExitPage( 'page2.html', true )
}

function trivUpdateTOC( currPage, parPage, bRecurse ) {
    var i
}

function trivUpdateEntry() {
}

function trivResetEntry() {
}

function action61(fn){
    trivExitPage('page2.html',true);
    if(fn) eval(fn);
}

function button61onUp() {
  action61();
}

function action60(fn){
    {cleanupTitle('page1'); trivExitPage('ObjLayerActionExit()',false);} 
    if(fn) eval(fn);
}

function button60onUp() {
  action60();
}

function action57(fn){
    text56.actionChangeContents(VarCurrentDate.getValue(),'alignleft','1'); 
    if(fn) eval(fn);
}

function text56actionShow() {
  setTimeout("if(!text56.isVisible()) { text56.objLyr.moveTo(text56.x, text56.y);text56.onShow();action57(); }", 1 )
}

if( is.min ){
button61 = new ObjButton('button61','Platinum Next',435,518,56,25,1,16,'div')
button61.setImages('images/platinum_nextoff.gif','images/platinum_nextclk.gif','images/platinum_nextrol.gif')
button61.onUp = button61onUp
button61.hasOnUp = true
button61.capture=4
button61.build()

button60 = new ObjButton('button60','Platinum Exit',385,516,28,28,1,17,'div')
button60.setImages('images/platinum_exitoff.gif','images/platinum_exitclk.gif','images/platinum_exitrol.gif')
button60.onUp = button60onUp
button60.hasOnUp = true
button60.capture=4
button60.build()

text56 = new ObjInline('text56',null,27,10,223,26,1,18,null,'div')
text56.actionShow = text56actionShow
text56.build()

image39 = new ObjImage('image39','images/shape_50.gif','Rectangle',311,569,158,22,1,19,'div')
image39.build()

text42 = new ObjInline('text42',null,183,116,427,47,1,20,null,'div')
text42.build()

image41 = new ObjImage('image41','images/image_4026_51.jpg','Image 4026',0,2,813,597,1,5,'div')
image41.build()



writeStyleSheets(
    button61.css+
    button60.css+
    text56.css+
    image39.css+
    text42.css+
    image41.css
    )
}
// -->

</script>
</head>

<body onfocus="trivOnFocus()" onResize="ReFlow()">

<script language="JavaScript">
if( is.min ){
    findWH()
    var left = (winW > 785) ? (winW-785)/2 : 0
    document.write('<style text="text/css">#pageDIV { position: absolute; top:0px; left: ' + left + 'px; width:785px; height:600px; ' )
    document.write('} ></style>')
    document.write('<DIV id=\"pageDIV\">')
}
</script>

<script language="JavaScript">
if( is.min ){
    document.write(button61.div)
    document.write(button60.div)
}
</script>

<div id="text56"><a name="text56anc"></a>
<p  style="margin-left:0px;text-indent:0px;margin-bottom:0px;margin-top:0px;text-align:left;" >
<span class="text56Font1" >date goes here</span ><span class="text56Font2" >
</span ></p >
</div>

<script language="JavaScript">
if( is.min ){
    document.write(image39.div)
}
</script>

<div id="text42"><a name="text42anc"></a>
<p  style="margin-left:36px;text-indent:-36px;margin-bottom:0px;margin-top:0px;text-align:center;" >
<span class="text42Font1" >New Products 2017
</span ></p >
</div>

<script language="JavaScript">
if( is.min ){
    document.write(image41.div)
    document.write("</DIV>")
}
</script>

</body>
</html>
